language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_740b25d5b0f1_key -iv $encrypted_740b25d5b0f1_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
