language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9b0b10211237_key -iv $encrypted_9b0b10211237_iv -in application.properties.enc -out src/main/resources/application.properties -d
